ALTER TABLE maintenances
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'OPEN';

ALTER TABLE maintenances
    ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP;

ALTER TABLE maintenances
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
