spring.application.name=valoreon

spring.main.web-application-type=servlet

server.servlet.context-path=/api
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari (pool)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=false

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}

# Refresh token
refresh.token.expiration-days=${REFRESH_TOKEN_EXPIRATION_DAYS:7}

# Cookie
cookie.secure=${COOKIE_SECURE:true}

# CORS
cors.origin=${CORS_ORIGIN:http://localhost:4200}

# Logs
logging.level.root=INFO
logging.level.org.springframework=INFO